%% cd016
mouse = 'cd016';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','H:\celine\cd016','sbxpath','W:\LabData4\celine\cd016',...
    'suite2ppath','H:\celine\cd016\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd016',...
    'behavpath','E:\KishoreLab\excitData\cd016\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd017
mouse = 'cd017';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','W:\LabData4\celine\cd017\h5','sbxpath','W:\LabData4\celine\cd017',...
    'suite2ppath','H:\celine\cd017\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd017',...
    'behavpath','E:\KishoreLab\excitData\cd017\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd036
mouse = 'cd036';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','V:\LabData5\cd036','sbxpath','V:\LabData5\cd036',...
    'suite2ppath','H:\celine\cd036\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd036',...
    'behavpath','E:\KishoreLab\excitData\cd036\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd037
mouse = 'cd037';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','V:\LabData5\cd037','sbxpath','V:\LabData5\cd037',...
    'suite2ppath','H:\celine\cd037\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd037',...
    'behavpath','E:\KishoreLab\excitData\cd037\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd042
mouse = 'cd042';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','S:\celine\cd042','sbxpath','S:\celine\cd042',...
    'suite2ppath','S:\celine\cd042\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd042',...
    'behavpath','E:\KishoreLab\excitData\cd042\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd044
mouse = 'cd044';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','S:\celine\cd044','sbxpath','S:\celine\cd044',...
    'suite2ppath','H:\celine\cd044\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd044',...
    'behavpath','E:\KishoreLab\excitData\cd044\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd019
mouse = 'cd019';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','R:\celine\cd019','sbxpath','W:\LabData4\celine\cd019',...
    'suite2ppath','R:\celine\cd019\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd019',...
    'behavpath','E:\KishoreLab\excitData\cd019\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd040
mouse = 'cd040';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','V:\LabData5\cd040','sbxpath','V:\LabData5\cd040',...
    'suite2ppath','V:\LabData5\cd040\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd040',...
    'behavpath','E:\KishoreLab\excitData\cd040\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% cd041
mouse = 'cd041';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','S:\celine\cd041','sbxpath','S:\celine\cd041',...
    'suite2ppath','H:\celine\cd041\suite2p',...
    'datapath','E:\KishoreLab\excitData\cd041',...
    'behavpath','E:\KishoreLab\excitData\cd041\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% zz017
mouse = 'zz017';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','S:\ziyi\zz017','sbxpath','S:\ziyi\zz017',...
    'suite2ppath','P:\ziyi\zz017\suite2p',...
    'datapath','E:\KishoreLab\excitData\zz017',...
    'behavpath','E:\KishoreLab\excitData\zz017\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% zz018
mouse = 'zz018';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','P:\ziyi\zz018','sbxpath','S:\ziyi\zz018',...
    'suite2ppath','P:\ziyi\zz018\suite2p',...
    'datapath','E:\KishoreLab\excitData\zz018',...
    'behavpath','E:\KishoreLab\excitData\zz018\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

%% zz019
mouse = 'zz019';
roiName =  ['roi\' mouse '_roi0.zip roi\' mouse '_roi1.zip'];
tcName =  ['TC\' mouse '_TC_plane0.mat TC\' mouse '_TC_plane1.mat'];
spikeFile = ['TC\' mouse '_spike_plane0.mat TC\'...
    mouse '_spike_plane1.mat'];

T = func_createMouseConfigNew(mouse,...
    'savepath','E:\KishoreLab\excitData\config\mouse',...
    'h5path','U:\LabData6\ziyi\zz019','sbxpath','U:\LabData6\ziyi\zz019',...
    'suite2ppath','H:\ziyi\zz019\suite2p',...
    'datapath','E:\KishoreLab\excitData\zz019',...
    'behavpath','E:\KishoreLab\excitData\zz019\behavior',...
    'roiFile',roiName,'tcFile',tcName,'spikeFile',spikeFile);

